### ISSUE TITLE
No such file or dir (Docker on Unraid)

### ISSUE THREAD

**Issue by BumbleCast** [niklasheld/zdf-download#1]
Thanks for the great docker. I hope that I am not too late asking a question.
I followed your explanation, but the log shows that the script can't find the output folder.
I get the following error:
No such file or directory: 'Fernsehen/ZDF Magazin Royale (2020)/Season 2022/

My Container path:
Container Path: /Fernsehen/
/mnt/user/TVShows/Fernsehen/

In the config yaml
  - feed-url: "https://www.zdf.de/rss/zdf/comedy/zdf-magazin-royale"
    filter:
      regex: "zdf-magazin-royale-vom-\\d"
      regexField: "link"
      minDate: "2022-10-27 00:00+00:00"
    download:
      folder: "/Fernsehen/ZDF Magazin Royale (2020)/Season 2022/"
      filename: "ZDF Magazin Royale"

No sure what's going wrong.
Thanks for any help!

**Comment by niklasheld** [comment]
Hi,
thanks for your feedback!
I'm not sure about the exact reason, but the issue seems to be caused by the way I invoked the `youtube-dl`-download using the subprocess module. Seems logical in hindsight, but I'm not sure why this issue didn't occur previously. The `latest` image should now work as expected.

A small disclaimer - I haven't been using and maintaining this application lately, so I can't gurantee that everything still works as intended. Using the RSS-feed as a source was a workaround to avoid having to scrape the actual web page of the ZDF-Mediathek and based on a quick look something has changed in there since last year. At least the `pubDate` entries in the feed don't seem to be correct, e.g. for episode "There's A Party".
If that is the case I think there is some work to be done in adjusting the application to use another, more reliable way, to get quick information about the episodes.

Let me know if this doesn't fix your issue.

**Comment by BumbleCast** [comment]
Hi,
thank you so much for your fast reply and help.
Everything works flawless after your changes. Again, thank you so much (also for spending parts of your Sunday on the issue).

Yes, I already thought that it could be potentially outdated. So far it seems to work. If I find any issue, I will report back!
